### ISSUE TITLE
broken matplotlib import? [a2]

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#229]
I have only written code for the first method in a2, and when I try to test it, I can't even run the test because the import is broken for some reason and I have no idea how to fix it.

From googling this error I found that this has something to do with matplotlib but I'm not exactly sure what's going on

ERROR: Failure: ImportError (libSM.so.6: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/david/anaconda3/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/david/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/david/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/david/anaconda3/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/david/anaconda3/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/c/Users/David/Desktop/cs579/a2/a2.py", line 28, in <module>
    import matplotlib.pyplot as plt
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/david/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

**Comment by ClaytonTurner** [comment]
This is peculiar. Did you try this: https://github.com/ContinuumIO/anaconda-issues/issues/244 ?

**Comment by davidghiurco** [comment]
This worked. It seems that this is an Ubuntu issue with conda. and I'm using the Ubuntu subsystem on windows for python development.

But I don't understand why it breaks on a2 but not on a0 which uses the same import..................
